### ISSUE TITLE
i suggest to use aptdat2sqlite.py instead

### ISSUE THREAD

**Issue by mherweg** [FGMEMBERS-SCENERY/xp850_to_fgaitm2#1]
yellow lines are not the best source for a groundnet.
apt.dat has real AI groundnets now. and here is the converter:
to Flightgear:

https://github.com/mherweg/d-laser-fgtools

aptdat2sqlite.py && sqlite2xml.py

**Comment by FGDATA** [comment]
Thanks D-LASER

I forked it then
How do you use it?

**Comment by mherweg** [comment]
like this:
aptdat2sqlite.py && sqlite2xml.py
there is a README.md too
